# **CARGA DE TRAIN Y TEST**

In [1]:
import numpy as np
import pandas as pd

In [2]:
x_train=pd.read_excel('05-x_train-RAVDESS-SINRUIDOSEXTREMOS-dato_audioopensmile.xlsx',index_col=0)
x_test=pd.read_excel('05-x_test-RAVDESS-SINRUIDOSEXTREMOS-dato_audioopensmile.xlsx',index_col=0)
y_train=pd.read_excel('05-y_train-RAVDESS-SINRUIDOSEXTREMOS-dato_audioopensmile.xlsx',index_col=0)
y_test=pd.read_excel('05-y_test-RAVDESS-SINRUIDOSEXTREMOS-dato_audioopensmile.xlsx',index_col=0)


# **BALANCEO DE DATOS**

In [3]:
#from imblearn.under_sampling import RandomUnderSampler
from imblearn.over_sampling import RandomOverSampler

In [4]:
overs = RandomOverSampler()

In [5]:
overs.fit(x_train, y_train)
x_t_overs, y_t_overs = overs.fit_resample(x_train, y_train)

In [6]:
y_t_overs

Emociones
0            1
1            3
2            3
3            3
4            3
..         ...
579          3
580          3
581          3
582          3
583          3

[584 rows x 1 columns]

# **MODELO DE MARCHINE LEARNING**

In [7]:

import keras
from tensorflow.keras.utils import to_categorical

from keras.models import Sequential # Arquitectura de la red
from keras.layers import Dense      # Capas de las redes neuronales
#from keras.layers import Dropout    # Regularizacion / Evita sobreajuste

clf = Sequential()
clf.add(Dense(512, activation='relu', input_dim=x_train.shape[1]))
clf.add(Dense(128, activation='relu'))
clf.add(Dense(32, activation='relu'))
clf.add(Dense(4, activation='softmax'))
# Compile the model
clf.compile(optimizer='adam', 
              loss='categorical_crossentropy', 
              metrics=['accuracy'])
clf.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 512)               13312     
                                                                 
 dense_1 (Dense)             (None, 128)               65664     
                                                                 
 dense_2 (Dense)             (None, 32)                4128      
                                                                 
 dense_3 (Dense)             (None, 4)                 132       
                                                                 
Total params: 83,236
Trainable params: 83,236
Non-trainable params: 0
_________________________________________________________________


In [8]:
# one hot encode outputs

y_t_Categorical = to_categorical(y_t_overs)
#y_test = to_categorical(y_test)

clf.fit(x_t_overs, y_t_Categorical , epochs=1500)
y_predict = clf.predict(x_test)

y_predict=np.argmax(y_predict, axis=1)
y_predict

#epochs
#680 R
#800 I
#1500 65
#2500 57
#4000 60 

Epoch 1/1500
19/19 [==============================] - 1s 4ms/step - loss: 75.0274 - accuracy: 0.2551
Epoch 2/1500
19/19 [==============================] - 0s 3ms/step - loss: 23.1765 - accuracy: 0.2877
Epoch 3/1500
19/19 [==============================] - 0s 3ms/step - loss: 9.6571 - accuracy: 0.3836
Epoch 4/1500
19/19 [==============================] - 0s 3ms/step - loss: 6.6191 - accuracy: 0.3818
Epoch 5/1500
19/19 [==============================] - 0s 3ms/step - loss: 7.3914 - accuracy: 0.3733
Epoch 6/1500
19/19 [==============================] - 0s 3ms/step - loss: 7.8709 - accuracy: 0.3562
Epoch 7/1500
19/19 [==============================] - 0s 3ms/step - loss: 8.6624 - accuracy: 0.3596
Epoch 8/1500
19/19 [==============================] - 0s 3ms/step - loss: 6.7695 - accuracy: 0.3990
Epoch 9/1500
19/19 [==============================] - 0s 3ms/step - loss: 5.0081 - accuracy: 0.4195
Epoch 10/1500
19/19 [==============================] - 0s 3ms/step - loss: 11.6726 - accuracy: 0.3

array([3, 0, 1, 1, 1, 3, 1, 3, 3, 1, 3, 3, 1, 3, 1, 1, 3, 0, 0, 1, 2, 3,
       3, 3, 3, 0, 3, 1, 1, 1, 1, 0, 2, 0, 3, 0, 3, 1, 0, 2, 0, 2, 1, 2,
       0, 3, 2, 0, 2, 3, 1, 1, 0, 3, 3, 0, 3, 0, 0, 3, 1, 1, 3, 3, 1, 0,
       1, 3, 1, 3, 2, 3, 2, 0, 3, 1, 3, 0, 0, 3, 1, 3, 3, 3, 3, 2, 1, 3,
       1, 3, 3, 3, 1, 0, 0, 1, 1, 0, 2, 1, 3, 1, 3, 3, 3, 3, 0, 0, 3, 1,
       0, 0, 3, 3, 1, 1, 2, 0, 0, 1, 0, 3, 3])

# **EVALUACION**

In [9]:
from sklearn.metrics import classification_report, confusion_matrix
print (classification_report(y_test, y_predict))

              precision    recall  f1-score   support

           0       0.83      0.62      0.71        39
           1       0.51      0.60      0.55        30
           2       0.42      0.45      0.43        11
           3       0.68      0.74      0.71        43

    accuracy                           0.64       123
   macro avg       0.61      0.60      0.60       123
weighted avg       0.66      0.64      0.65       123



In [10]:
from sklearn.metrics import classification_report, confusion_matrix
import itertools
import matplotlib.pyplot as plt
def plot_confusion_matrix(cm, classes,
                          normalize=False,
                          title='Confusion matrix',
                          cmap=plt.cm.Blues):
    """
    Esta función imprime y marca la matriz de confusión.
    Se puede aplicar Normalización seteando la variable `normalize=True`.
    """
    if normalize:
        cm = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis]
        print("Normalized confusion matrix")
    else:
        print('Matriz de confusión, sin normalización')

    print(cm)

    plt.imshow(cm, interpolation='nearest', cmap=cmap)
    plt.title(title)
    plt.colorbar()
    tick_marks = np.arange(len(classes))
    plt.xticks(tick_marks, classes, rotation=45)
    plt.yticks(tick_marks, classes)

    fmt = '.2f' if normalize else 'd'
    thresh = cm.max() / 2.
    for i, j in itertools.product(range(cm.shape[0]), range(cm.shape[1])):
        plt.text(j, i, format(cm[i, j], fmt),
                 horizontalalignment="center",
                 color="white" if cm[i, j] > thresh else "black")

    plt.tight_layout()
    plt.ylabel('Etiqueta True')
    plt.xlabel('Etiqueta predecida')

In [11]:
# Computar la matriz de confusión
cnf_matrix = confusion_matrix(y_test, y_predict, labels=[0,1,2,3])
np.set_printoptions(precision=2)

print (classification_report(y_test, y_predict))

# Plot non-normalized confusion matrix
plt.figure()
plot_confusion_matrix(cnf_matrix, classes=['angry:0','happy:1','Neutral:2','sad:3',],normalize= False,  title='Matriz de confusión')

              precision    recall  f1-score   support

           0       0.83      0.62      0.71        39
           1       0.51      0.60      0.55        30
           2       0.42      0.45      0.43        11
           3       0.68      0.74      0.71        43

    accuracy                           0.64       123
   macro avg       0.61      0.60      0.60       123
weighted avg       0.66      0.64      0.65       123

Matriz de confusión, sin normalización
[[24 10  3  2]
 [ 3 18  1  8]
 [ 0  1  5  5]
 [ 2  6  3 32]]
